### ISSUE TITLE
Create Zenodo DOI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#114]
We should have each release uploaded to Zenodo and a DOI created for it.

**Comment by bernhardmgruber** [comment]
I cannot connect Zenodo to the Github LLAMA repository, because I do not have the rights to allow Zenodo to access the repository.

@psychocoderHPC, @BenjaminW3 or @ax3l: you are listed as admins of the alpaka-group. Could someone of you please grant access to Zenodo? Here is a guide: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization
You might not see a Zenodo request, because I cannot create one from my Zenodo account :/

Thank you!

**Comment by bernhardmgruber** [comment]
The Github integration on Zenodo is now enabled. However, no DOI has been created yet for any of the previous releases.

**Comment by psychocoderHPC** [comment]
If you go to the release page than edit the last commit and store (no changes) the event should be fired again. If you have a DOI please add this DOI to the release nodes

**Comment by bernhardmgruber** [comment]
The Zenodo hook was triggered during the last release, but there were errors on the Zenodo side:
```JSON
{
    "errors": "{'metadata': {'grants': [u'Invalid grant ID(s): 10.13039/501100000780::05E18CHA'], 'contributors': {0: {'type': [u'Missing data for required field.']}, 1: {'type': [u'Missing data for required field.']}, 2: {'type': [u'Missing data for required field.']}}}}"
}
```

**Comment by ax3l** [comment]
The errors are on our side, I fear.

The `contributors` need a `type` field, e.g.:
https://github.com/alpaka-group/llama/blob/c60373bfa4ce28b46a3889cbd728d5a73671e0fd/.zenodo.json#L21-L34
vs.
https://github.com/openPMD/openPMD-api/blob/34b24d92f262590f3da2e5d587e5904640fd76d8/.rodare.json#L29

And one of the grant ID is invalid:
https://github.com/alpaka-group/llama/blob/develop/.zenodo.json#L50

Maybe remove the grants, add them for the first release manually, then export the JSON file and check their correct IDs for the `.zenodo.json` file.

**Comment by bernhardmgruber** [comment]
Thank you @ax3l! That is really helpful! I will give your suggestions a try!
