### ISSUE TITLE
Implement a SIMD for_each

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#169]
LLAMA is a library for efficient memory layouts and memory access patterns. For CPUs, this is only half the story. The second half is filling vector registers to also optimize the compute throughput. While this should not  be directly handled by LLAMA, LLAMA certainly can provide useful data layouts and should allow for some algorithmic primitives on top.

After thinking some time on this topic and rereading some stuff from Matthias Kretz on Vc and std::simd, I think these primitives are going to be the SIMD variants of the STL algorithms, as proposed here: http://wg21.link/P0350.

Modified example from P0350:
```c++
template <class T>
T something(T); // T can by float or std::simd<float>

auto f(const std::vector<float>& data) {
  std::vector<float> output;
  stdx::transform(std::execution::simd,
    data.begin(), data.end(), output.begin(),
    [](auto x) { // type of x can by float or std::simd<float>
      return something(x + 1);
    });
  return output;
}
```

I think just having a `for_each` in this fassion could already be quite useful. Even more useful, if we would allow the lambda argument to be a mutable reference allowing write-back to memory. Depending on the data layout and target architecture, we could then run the lambda with SIMD vectors or scalars.

**Comment by bussmann** [comment]
How does this interface to vicunja?

**Comment by bernhardmgruber** [comment]
We discussed this today in the alpaka VC and we are going to need a dedicated meeting on this. We can see this functionality in Vikunja, because it will likely use such a SIMD loop at the very bottom. However, Vikunja has a dependency on alpaka, so then we cannot have a SIMD loop without alpaka, threads or accelerators. If the SIMD loop stays in Vikunja, we also need to communiate a *lot* of information from LLAMA to Vikunja. In LLAMA, it would integrate quite well. However, we also agree that such a SIMD loop is something on a higher level than the core functionality of LLAMA which is providing memory layouts. We also considered a separate library for just the SIMD loop.

**Comment by bussmann** [comment]
I would clearly opt to keep algorithms out of Llama. Thus SIMD for_each should be placed into a helper library.

**Comment by bernhardmgruber** [comment]
The `llama::Some<Record>` construct could render this feature obsolete: #295.

**Comment by bernhardmgruber** [comment]
There is a `simd_for_each` in `Vc`: https://github.com/VcDevel/Vc/blob/1.4/Vc/common/algorithms.h#L64
