### ISSUE TITLE
Add nvc++ to the CI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#203]
@ax3l mentioned a couple of relevant HPC compilers [here](https://github.com/alpaka-group/alpaka/issues/1296#issuecomment-823861871). LLAMA already tests with all publicly available ones, except for the new nvc++ from NVIDIA.

nvc++ recently started to support CUDA as well, so it can be used as a host and device compiler (much like clang). We should add it to the CI.

**Comment by ax3l** [comment]
You could also check `hip` and potentially alongside the existing `icpx` a `dpcpp` test.

**Comment by jkelling** [comment]
You can assign this issue to me, I am planning to do this for the OpenACC backend anyway.

**Comment by bernhardmgruber** [comment]
I am happy for any new compiler you can add! :)

**Comment by jkelling** [comment]
Is it possible, that this issue is located in this wrong repo? [The discussion](https://github.com/alpaka-group/alpaka/issues/1296#issuecomment-823861871) mentioned above belongs to alpaka not llama...

**Comment by bernhardmgruber** [comment]
No, this issue is in the right place ;) And I am awaiting your PR on adding nvc++ to LLAMA's CI! :D

**Comment by jkelling** [comment]
You can copy the Alpaka Ci config, once it is in there.;) . That should not be problematic, right? I am not familiar with Llama.

**Comment by bernhardmgruber** [comment]
This issue is now blocked by the Vc SIMD library, see #547. So we need to solve #520 first.
