### ISSUE TITLE
Small documentation bugs

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/llama#217]
Here is a list of small bugs, which I found during reading the documentation.

* https://llama-doc.readthedocs.io/en/latest/pages/introduction.html#goals : `?` displayed instead `'`, e.g.: `structure?s`
* https://llama-doc.readthedocs.io/en/latest/pages/virtualrecord.html#one : code block missing
* https://llama-doc.readthedocs.io/en/latest/pages/virtualrecord.html#arithmetic-and-logical-operatores : in the third code block I believe some types for variable declaration are missing, e.g.: `a1(x{}) = 0.0f;`
* https://llama-doc.readthedocs.io/en/latest/pages/virtualrecord.html#structured-bindings : code highlighting failed

**Comment by bernhardmgruber** [comment]
Wow, that's great! Thank you very much for finding these! I will update the docs accordingly soon!

**Comment by bernhardmgruber** [comment]
I am not sure I fully understood the 3. point. I replaced this comment:
```
// Let assume a1 and a2 using A and b using B.
```
by the following declarations:
```
    llama::One<A> a1, a2;
    llama::One<B> b;
```
That should make it more clear what the variables are. Does this address your comment?

**Comment by SimeonEhrig** [comment]
Yes, that's address my issue. I didn't really recognize the comment. In the end, I understand the example in general. It was only inconsistent compare to the other code examples.

**Comment by bernhardmgruber** [comment]
Perfect, thank you again for finding these!

**Comment by SimeonEhrig** [comment]
Sorry for being late with the review, but I see, that you forgot some question marks in the `introduction.rst`. If you open the raw view on GitHub, you can find it easily: https://raw.githubusercontent.com/bernhardmgruber/llama/4eb58447b1a1a13b23e51cb6228cab70f161e932/docs/pages/introduction.rst

**Comment by bernhardmgruber** [comment]
I really wonder how these happen. I cannot even type this type of apostrophe. I will have a look!

**Comment by SimeonEhrig** [comment]
I was also surprised as I saw the diff of the commit.
