### ISSUE TITLE
stack allocation method for DS, DE, ...

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/llama#29]
- add method to llama::DS (llama::DE?, ..) to allocate object on the stack
```c++
auto temp = llama::stackVirtualDatumAlloc< Particle >( );
// =>
auto temp = Particle::alloc(); // stack only
```
@bertwesarg

**Comment by bertwesarg** [comment]
`llama:DS` and co are of type `boost::mp11::mp_list`, thus we cannot add static functions to this type, can we?

**Comment by ax3l** [comment]
just create free-standing `static` functions instead, such as `make_...`?

**Comment by bertwesarg** [comment]
> just create free-standing `static` functions instead, such as `make_...`?

`llama::stackVirtualDatumAlloc` is a _free-standing `static` function_, isn't it? And I consider it rather ugly.

Could we implement `llama:DS` and co as an derived type of `boost::mp11::mp_list` instead of just being a `using`? That should give us the possibility to add `static` functions to the type.

**Comment by ax3l** [comment]
That's possible as well, yet the [C++ standard library](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared) and some [exceptionally awesome recent C++ libs](https://xtensor.readthedocs.io/en/latest/numpy.html) use free standing functions quite regularly, especially for factories/generators, and I think it's not that ugly but more a forgotten art.

Deriving publicly from something std-library-ish things like `std::vector` is discouraged, yet I am not sure how this applies to metaprogramming aspects. IIRC, `boost::mp11::mp_list` is a potential std library candidate.

**Comment by bernhardmgruber** [comment]
The current mechanism for a scalar record on the stack is `llama::One<Particle> p;` and I consider it good enough for now.

Please open a new ticket or reopen another ticket if you would like to encourage or suggest further improvements on this feature!
