### ISSUE TITLE
Some<Record> a construct for some elements and SIMD

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#295]
LLAMA has the `One<Record>` construct to hold and manipulate a single record. To facilitate SIMD programming models, we would need a construct to hold several records, depending on the target hardware architecture and the given record dimension. We should explore adding a `Some<Record>` construct representing a bunch of records.

Whether `Some<Record>` should expose a size is an open question: `Some<Record, N>`.

`Some<Record>` for CPU targets should create a structure of SIMD vectors and thus should integrate with SIMD libraries like Vc or `std::simd`. But it should neither require a SIMD library (GPU targets) or become a SIMD library (mission creep). The interaction is mostly on how to store from any mapping into SIMD vectors. Whether that is efficient or not depends on the mapping (e.g. vector fetches vs. gather/scatter vs. individual loads).

A design aspect is how to differentiate a scalar access from a vector access. This information also needs to be carried through the VirtualRecord's created on the way until the access is terminal.

I believe this construct could solve the inefficiency of the AoSoA mapping, which is slow when individual elements are accessed. But when `Some<Records>`s are read from an AoSoA with matching lane length, access could be a lot better. Furthermore, this construct is a good building block on how algorithms could be designed to be SIMD friendly and a stepping stone towards a vectorizable kernel language.

**Comment by j-stephan** [comment]
Sounds interesting. Regarding the naming: Maybe rename `One` to `Scalar` and `Some` to `Vector`?

**Comment by bernhardmgruber** [comment]
We could add access modifiers during the index specification:
```c++
auto x = view(32)(Pos{})(X{}); // returns scalar value
auto xs = view(SomeFrom{32})(Pos{})(X{}); // returns SIMD value

auto vr = view(SomeFrom{32}); // a VirtualRecord carrying information that a SIMD access is requested.
```
Or queue them up:
```c++
auto x = view(32)(Pos{})(X{}); // returns scalar value
auto xs = view(AsSome{})(32)(Pos{})(X{}); // returns SIMD value
auto vr = view(AsSome{})(32); // returns SIMD VirtualRecord
```
The latter design would allow us to generally support access modifiers as tag types. These would be held by all `VirtualRecord`s constructed until the access is terminal, where these access modifiers would be passed to the mapping, allowing the mapping to apply a different mapping function depending on the access modifiers.
The latter is really important for the AoSoA, because it can avoid a masking operation when it knows that SIMD access is desired. This could allow the compiler to better optimize the code, giving AoSoA the speed it deserves.
SoA would also work immediately. How AoS could then create a scatter/gather is still unclear to me.

**Comment by bernhardmgruber** [comment]
This idea can be extended to not only SIMD but a general bulk data API. It turns out the Bitpack mappings are fairly slow because each element is unpacked/repacked individually upon access. They could benefit tremendously if we unpack/repack multiple elements in bulk.
