### ISSUE TITLE
Forgot to include in tests/common.h

### ISSUE THREAD

**Issue by bboysnick5** [alpaka-group/llama#303]
Need to include `#include <sstream>` in tests/common.h in order for tests to compile. Otherwise line 37 `std::stringstream rawSS(raw);` will trigger compile time error.

**Comment by bernhardmgruber** [comment]
Thank you for spotting this! A fix is coming: #304.

I wonder though since the CI passed in the past: What compiler are you using? Maybe I should add that one! Thank you!

**Comment by bboysnick5** [comment]
Mac clang trunk. Also I think you should add additional dependencies for tests and examples to build, such as catch2 and openmp 5.1 in documents. Otherwise they won't compile either.

**Comment by bernhardmgruber** [comment]
> Mac clang trunk.

Thank you! This is related to #297 then. I'll try to get the MacOS CI sooner then.

> Also I think you should add additional dependencies for tests and examples to build, such as catch2 and openmp 5.1 in documents. Otherwise they won't compile either.

We list the required dependencies in the documentation here: https://llama-doc.readthedocs.io/en/latest/pages/install.html#dependencies
We could consider adding them to the README.md as well. OpenMP 5.1 should not be required though, I think OpenMP 2.0 is enough. It might also be the case that Vc is required in the meantime for some examples. You can install those with your favorite package manager!
