### ISSUE TITLE
Add meta mapping permuting indices

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#381]
In PIConGPU we have algorithms expressed in a certain coordinate system, but the algorithm is also run on the same multi-dimensional data with permuted coordinate axes. To easily support this, we should add a wrapper that permutes the `ArrayDims` on access and forwards the access to an inner mapping.

**Comment by bussmann** [comment]
Now this is a great first step. When accessing data in certain ways from user side, we sometimes do not need to change the algorithm itself, but the way it traverses the data used.

Examples include stencils, the switch of coordinate system you mention here, or the switch of topology of a computing grid (e.g. mesh refinement, switch from cartesian to tetrahedal mesh, change of graph connections, ...). While originally not (primarily) intended for this, LLAMA can help disentangle data representation from algorithm even for these cases (there are numerous ways to discretize a space to solve a PDE).

Now one way to approach this would be to create complex mappings by concatenating simple mappings. In your example, the permutation of the coordinate axes is a first mapping, the next is then the one to the memory representation. The concept of concatenated mappings is very powerful.
