### ISSUE TITLE
Consider replacing Vc as SIMD library

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#520]
Development of Vc has stopped for a while, since the effort has moved to std::simd. The dependency is also heavy on the CI. We should consider replacing it by either a different SIMD library or just `std::experimental::simd` directly.

**Comment by bussmann** [comment]
std::

**Comment by bernhardmgruber** [comment]
The problem with `std::experimental::simd` is that it is still experimental and not widely supported. AFAIK only libstdc++ has an implementation yet. This would lock us into Linux only for the concerning examples. While Windows is not an important run target, it is still great to debug there. And Apple has interesting hardware recently, so it would be a shame if we could not run on e.g. an M1.

**Comment by bernhardmgruber** [comment]
I tried `xsimd` quickly and it lacks an API to write a single element of a SIMD vector.

**Comment by bernhardmgruber** [comment]
> I tried `xsimd` quickly and it lacks an API to write a single element of a SIMD vector.

That is solved now.

**Comment by bernhardmgruber** [comment]
`Vc` now blocks the usage of `nvc++` as compiler.
